creation_rules:
  - age: >-
      age1krnn9a73tl2fgpms3tkyl8ymc6ms46r2saynndwxe7rvvkyhgvtskdz9zs,
      age1zkxrdqwqrpekvve8anjs5udzzqgmv0uasxjyfu3hhh6f9rxrl5uq5qhzrx,
      age15fc75hw2q24pcjpe0xu4twdsa3fdul5vt8whv339y2wafrkdh5jqmywgjh