// Code generated by ogen, DO NOT EDIT.

package api

// APIV2AuthReferenceNumberGetParams is parameters of GET /api/v2/auth/{referenceNumber} operation.
type APIV2AuthReferenceNumberGetParams struct {
	// Numer referencyjny tokena otrzymanego przy inicjalizacji operacji uwierzytelniania.
	ReferenceNumber ReferenceNumber
}

// APIV2AuthSessionsGetParams is parameters of GET /api/v2/auth/sessions operation.
type APIV2AuthSessionsGetParams struct {
	// Token służący do pobrania kolejnej strony wyników.
	XContinuationToken OptString `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// APIV2AuthSessionsReferenceNumberDeleteParams is parameters of DELETE /api/v2/auth/sessions/{referenceNumber} operation.
type APIV2AuthSessionsReferenceNumberDeleteParams struct {
	// Numer referencyjny sesji uwierzytelnienia.
	ReferenceNumber ReferenceNumber
}

// APIV2AuthXadesSignaturePostParams is parameters of POST /api/v2/auth/xades-signature operation.
type APIV2AuthXadesSignaturePostParams struct {
	// Wymuszenie weryfikacji zaufania łańcucha certyfikatu wraz ze sprawdzeniem statusu certyfikatu
	// (OCSP/CRL) na środowiskach które umożliwiają wykorzystanie samodzielnie wygenerowanych
	// certyfikatów.
	VerifyCertificateChain OptBool `json:",omitempty,omitzero"`
}

// APIV2CertificatesCertificateSerialNumberRevokePostParams is parameters of POST /api/v2/certificates/{certificateSerialNumber}/revoke operation.
type APIV2CertificatesCertificateSerialNumberRevokePostParams struct {
	// Numer seryjny certyfikatu (w formacie szesnastkowym).
	CertificateSerialNumber string
}

// APIV2CertificatesEnrollmentsReferenceNumberGetParams is parameters of GET /api/v2/certificates/enrollments/{referenceNumber} operation.
type APIV2CertificatesEnrollmentsReferenceNumberGetParams struct {
	// Numer referencyjny wniosku certyfikacyjnego.
	ReferenceNumber ReferenceNumber
}

// APIV2CertificatesQueryPostParams is parameters of POST /api/v2/certificates/query operation.
type APIV2CertificatesQueryPostParams struct {
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
}

// APIV2InvoicesExportsReferenceNumberGetParams is parameters of GET /api/v2/invoices/exports/{referenceNumber} operation.
type APIV2InvoicesExportsReferenceNumberGetParams struct {
	// Numer referencyjny eksportu faktur.
	ReferenceNumber ReferenceNumber
}

// APIV2InvoicesKsefKsefNumberGetParams is parameters of GET /api/v2/invoices/ksef/{ksefNumber} operation.
type APIV2InvoicesKsefKsefNumberGetParams struct {
	// Numer KSeF faktury.
	KsefNumber KsefNumber
}

// APIV2InvoicesQueryMetadataPostParams is parameters of POST /api/v2/invoices/query/metadata operation.
type APIV2InvoicesQueryMetadataPostParams struct {
	// Kolejność sortowania wyników.
	// | Wartość | Opis |
	// | --- | --- |
	// | Asc | Sortowanie rosnąco. |
	// | Desc | Sortowanie malejąco. |.
	SortOrder OptSortOrder `json:",omitempty,omitzero"`
	// Indeks pierwszej strony wyników (0 = pierwsza strona).
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// APIV2PeppolQueryGetParams is parameters of GET /api/v2/peppol/query operation.
type APIV2PeppolQueryGetParams struct {
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// APIV2PermissionsAuthorizationsGrantsPermissionIdDeleteParams is parameters of DELETE /api/v2/permissions/authorizations/grants/{permissionId} operation.
type APIV2PermissionsAuthorizationsGrantsPermissionIdDeleteParams struct {
	// Id uprawnienia.
	PermissionId PermissionId
}

// APIV2PermissionsCommonGrantsPermissionIdDeleteParams is parameters of DELETE /api/v2/permissions/common/grants/{permissionId} operation.
type APIV2PermissionsCommonGrantsPermissionIdDeleteParams struct {
	// Id uprawnienia.
	PermissionId PermissionId
}

// APIV2PermissionsOperationsReferenceNumberGetParams is parameters of GET /api/v2/permissions/operations/{referenceNumber} operation.
type APIV2PermissionsOperationsReferenceNumberGetParams struct {
	// Numer referencyjny operacji nadania lub odbierania uprawnień.
	ReferenceNumber ReferenceNumber
}

// APIV2PermissionsQueryAuthorizationsGrantsPostParams is parameters of POST /api/v2/permissions/query/authorizations/grants operation.
type APIV2PermissionsQueryAuthorizationsGrantsPostParams struct {
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// APIV2PermissionsQueryEntitiesRolesGetParams is parameters of GET /api/v2/permissions/query/entities/roles operation.
type APIV2PermissionsQueryEntitiesRolesGetParams struct {
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// APIV2PermissionsQueryEuEntitiesGrantsPostParams is parameters of POST /api/v2/permissions/query/eu-entities/grants operation.
type APIV2PermissionsQueryEuEntitiesGrantsPostParams struct {
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// APIV2PermissionsQueryPersonalGrantsPostParams is parameters of POST /api/v2/permissions/query/personal/grants operation.
type APIV2PermissionsQueryPersonalGrantsPostParams struct {
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// APIV2PermissionsQueryPersonsGrantsPostParams is parameters of POST /api/v2/permissions/query/persons/grants operation.
type APIV2PermissionsQueryPersonsGrantsPostParams struct {
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// APIV2PermissionsQuerySubordinateEntitiesRolesPostParams is parameters of POST /api/v2/permissions/query/subordinate-entities/roles operation.
type APIV2PermissionsQuerySubordinateEntitiesRolesPostParams struct {
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// APIV2PermissionsQuerySubunitsGrantsPostParams is parameters of POST /api/v2/permissions/query/subunits/grants operation.
type APIV2PermissionsQuerySubunitsGrantsPostParams struct {
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// APIV2SessionsBatchReferenceNumberClosePostParams is parameters of POST /api/v2/sessions/batch/{referenceNumber}/close operation.
type APIV2SessionsBatchReferenceNumberClosePostParams struct {
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
}

// APIV2SessionsGetParams is parameters of GET /api/v2/sessions operation.
type APIV2SessionsGetParams struct {
	// Rozmiar strony.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Typ sesji.
	// | Wartość | Opis |
	// | --- | --- |
	// | Online | Wysyłka interaktywna (pojedyncze faktury). |
	// | Batch | Wysyłka wsadowa (paczka faktur). |.
	SessionType SessionType
	// Numer referencyjny sesji.
	ReferenceNumber OptReferenceNumber `json:",omitempty,omitzero"`
	// Data utworzenia sesji (od).
	DateCreatedFrom OptDateTime `json:",omitempty,omitzero"`
	// Data utworzenia sesji (do).
	DateCreatedTo OptDateTime `json:",omitempty,omitzero"`
	// Data zamknięcia sesji (od).
	DateClosedFrom OptDateTime `json:",omitempty,omitzero"`
	// Data zamknięcia sesji (do).
	DateClosedTo OptDateTime `json:",omitempty,omitzero"`
	// Data ostatniej aktywności (wysyłka faktury lub zmiana statusu) w ramach sesji (od).
	DateModifiedFrom OptDateTime `json:",omitempty,omitzero"`
	// Data ostatniej aktywności (wysyłka faktury lub zmiana statusu) w ramach sesji (do).
	DateModifiedTo OptDateTime `json:",omitempty,omitzero"`
	// Statusy sesji.
	// | Wartość | Opis |
	// | --- | --- |
	// | InProgress | Sesja aktywna. |
	// | Succeeded | Sesja przetworzona poprawnie.            W trakcie przetwarzania sesji nie
	// wystąpiły żadne błędy, ale część faktur nadal mogła zostać odrzucona. |
	// | Failed | Sesja nie przetworzona z powodu błędów.            Na etapie rozpoczynania lub
	// kończenia sesji wystąpiły błędy, które nie pozwoliły na jej poprawne przetworzenie. |
	// | Cancelled | Sesja anulowania.            Został przekroczony czas na wysyłkę w sesji wsadowej,
	//  lub nie przesłano żadnych faktur w sesji interaktywnej. |.
	Statuses []CommonSessionStatus `json:",omitempty"`
	// Token służący do pobrania kolejnej strony wyników.
	XContinuationToken OptString `json:",omitempty,omitzero"`
}

// APIV2SessionsOnlineReferenceNumberClosePostParams is parameters of POST /api/v2/sessions/online/{referenceNumber}/close operation.
type APIV2SessionsOnlineReferenceNumberClosePostParams struct {
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
}

// APIV2SessionsOnlineReferenceNumberInvoicesPostParams is parameters of POST /api/v2/sessions/online/{referenceNumber}/invoices operation.
type APIV2SessionsOnlineReferenceNumberInvoicesPostParams struct {
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
}

// APIV2SessionsReferenceNumberGetParams is parameters of GET /api/v2/sessions/{referenceNumber} operation.
type APIV2SessionsReferenceNumberGetParams struct {
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
}

// APIV2SessionsReferenceNumberInvoicesFailedGetParams is parameters of GET /api/v2/sessions/{referenceNumber}/invoices/failed operation.
type APIV2SessionsReferenceNumberInvoicesFailedGetParams struct {
	// Token służący do pobrania kolejnej strony wyników.
	XContinuationToken OptString `json:",omitempty,omitzero"`
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// APIV2SessionsReferenceNumberInvoicesGetParams is parameters of GET /api/v2/sessions/{referenceNumber}/invoices operation.
type APIV2SessionsReferenceNumberInvoicesGetParams struct {
	// Token służący do pobrania kolejnej strony wyników.
	XContinuationToken OptString `json:",omitempty,omitzero"`
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// APIV2SessionsReferenceNumberInvoicesInvoiceReferenceNumberGetParams is parameters of GET /api/v2/sessions/{referenceNumber}/invoices/{invoiceReferenceNumber} operation.
type APIV2SessionsReferenceNumberInvoicesInvoiceReferenceNumberGetParams struct {
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
	// Numer referencyjny faktury.
	InvoiceReferenceNumber ReferenceNumber
}

// APIV2SessionsReferenceNumberInvoicesInvoiceReferenceNumberUpoGetParams is parameters of GET /api/v2/sessions/{referenceNumber}/invoices/{invoiceReferenceNumber}/upo operation.
type APIV2SessionsReferenceNumberInvoicesInvoiceReferenceNumberUpoGetParams struct {
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
	// Numer referencyjny faktury.
	InvoiceReferenceNumber ReferenceNumber
}

// APIV2SessionsReferenceNumberInvoicesKsefKsefNumberUpoGetParams is parameters of GET /api/v2/sessions/{referenceNumber}/invoices/ksef/{ksefNumber}/upo operation.
type APIV2SessionsReferenceNumberInvoicesKsefKsefNumberUpoGetParams struct {
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
	// Numer KSeF faktury.
	KsefNumber KsefNumber
}

// APIV2SessionsReferenceNumberUpoUpoReferenceNumberGetParams is parameters of GET /api/v2/sessions/{referenceNumber}/upo/{upoReferenceNumber} operation.
type APIV2SessionsReferenceNumberUpoUpoReferenceNumberGetParams struct {
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
	// Numer referencyjny UPO.
	UpoReferenceNumber ReferenceNumber
}

// APIV2TokensGetParams is parameters of GET /api/v2/tokens operation.
type APIV2TokensGetParams struct {
	// Status tokenów do zwrócenia. W przypadku braku parametru zwracane są wszystkie tokeny. Parametr
	// można przekazać wielokrotnie.
	// | Wartość | Opis |
	// | --- | --- |
	// | Pending | Token został utworzony ale jest jeszcze w trakcie aktywacji i nadawania uprawnień.
	// Nie może być jeszcze wykorzystywany do uwierzytelniania. |
	// | Active | Token jest aktywny i może być wykorzystywany do uwierzytelniania. |
	// | Revoking | Token jest w trakcie unieważniania. Nie może już być wykorzystywany do
	// uwierzytelniania. |
	// | Revoked | Token został unieważniony i nie może być wykorzystywany do uwierzytelniania. |
	// | Failed | Nie udało się aktywować tokena. Należy wygenerować nowy token, obecny nie może
	// być wykorzystywany do uwierzytelniania. |.
	Status []AuthenticationTokenStatus `json:",omitempty"`
	// Umożliwia filtrowanie tokenów po opisie. Wartość parametru jest wyszukiwana w opisie tokena
	// (operacja nie rozróżnia wielkości liter). Należy podać co najmniej 3 znaki.
	Description OptString `json:",omitempty,omitzero"`
	// Umożliwia filtrowanie tokenów po ich twórcy. Wartość parametru jest wyszukiwana w
	// identyfikatorze (operacja nie rozróżnia wielkości liter). Należy podać co najmniej 3 znaki.
	AuthorIdentifier OptString `json:",omitempty,omitzero"`
	// Umożliwia filtrowanie tokenów po ich twórcy. Wartość parametru określa typ identyfikatora w
	// którym będzie wyszukiwany ciąg znaków przekazany w parametrze `authorIdentifier`.
	// | Wartość | Opis |
	// | --- | --- |
	// | Nip | NIP. |
	// | Pesel | PESEL. |
	// | Fingerprint | Odcisk palca certyfikatu. |.
	AuthorIdentifierType OptTokenAuthorIdentifierType `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Token służący do pobrania kolejnej strony wyników.
	XContinuationToken OptString `json:",omitempty,omitzero"`
}

// APIV2TokensReferenceNumberDeleteParams is parameters of DELETE /api/v2/tokens/{referenceNumber} operation.
type APIV2TokensReferenceNumberDeleteParams struct {
	// Numer referencyjny tokena KSeF.
	ReferenceNumber ReferenceNumber
}

// APIV2TokensReferenceNumberGetParams is parameters of GET /api/v2/tokens/{referenceNumber} operation.
type APIV2TokensReferenceNumberGetParams struct {
	// Numer referencyjny tokena KSeF.
	ReferenceNumber ReferenceNumber
}
