// Code generated by ogen, DO NOT EDIT.
package api

type APIV2AuthChallengePostRes interface {
	aPIV2AuthChallengePostRes()
}

type APIV2AuthKsefTokenPostRes interface {
	aPIV2AuthKsefTokenPostRes()
}

type APIV2AuthReferenceNumberGetRes interface {
	aPIV2AuthReferenceNumberGetRes()
}

type APIV2AuthSessionsCurrentDeleteRes interface {
	aPIV2AuthSessionsCurrentDeleteRes()
}

type APIV2AuthSessionsGetRes interface {
	aPIV2AuthSessionsGetRes()
}

type APIV2AuthSessionsReferenceNumberDeleteRes interface {
	aPIV2AuthSessionsReferenceNumberDeleteRes()
}

type APIV2AuthTokenRedeemPostRes interface {
	aPIV2AuthTokenRedeemPostRes()
}

type APIV2AuthTokenRefreshPostRes interface {
	aPIV2AuthTokenRefreshPostRes()
}

type APIV2AuthXadesSignaturePostRes interface {
	aPIV2AuthXadesSignaturePostRes()
}

type APIV2CertificatesCertificateSerialNumberRevokePostRes interface {
	aPIV2CertificatesCertificateSerialNumberRevokePostRes()
}

type APIV2CertificatesEnrollmentsDataGetRes interface {
	aPIV2CertificatesEnrollmentsDataGetRes()
}

type APIV2CertificatesEnrollmentsPostRes interface {
	aPIV2CertificatesEnrollmentsPostRes()
}

type APIV2CertificatesEnrollmentsReferenceNumberGetRes interface {
	aPIV2CertificatesEnrollmentsReferenceNumberGetRes()
}

type APIV2CertificatesLimitsGetRes interface {
	aPIV2CertificatesLimitsGetRes()
}

type APIV2CertificatesQueryPostRes interface {
	aPIV2CertificatesQueryPostRes()
}

type APIV2CertificatesRetrievePostRes interface {
	aPIV2CertificatesRetrievePostRes()
}

type APIV2InvoicesExportsPostRes interface {
	aPIV2InvoicesExportsPostRes()
}

type APIV2InvoicesExportsReferenceNumberGetRes interface {
	aPIV2InvoicesExportsReferenceNumberGetRes()
}

type APIV2InvoicesKsefKsefNumberGetRes interface {
	aPIV2InvoicesKsefKsefNumberGetRes()
}

type APIV2InvoicesQueryMetadataPostRes interface {
	aPIV2InvoicesQueryMetadataPostRes()
}

type APIV2LimitsContextGetRes interface {
	aPIV2LimitsContextGetRes()
}

type APIV2LimitsSubjectGetRes interface {
	aPIV2LimitsSubjectGetRes()
}

type APIV2PeppolQueryGetRes interface {
	aPIV2PeppolQueryGetRes()
}

type APIV2PermissionsAttachmentsStatusGetRes interface {
	aPIV2PermissionsAttachmentsStatusGetRes()
}

type APIV2PermissionsAuthorizationsGrantsPermissionIdDeleteRes interface {
	aPIV2PermissionsAuthorizationsGrantsPermissionIdDeleteRes()
}

type APIV2PermissionsAuthorizationsGrantsPostRes interface {
	aPIV2PermissionsAuthorizationsGrantsPostRes()
}

type APIV2PermissionsCommonGrantsPermissionIdDeleteRes interface {
	aPIV2PermissionsCommonGrantsPermissionIdDeleteRes()
}

type APIV2PermissionsEntitiesGrantsPostRes interface {
	aPIV2PermissionsEntitiesGrantsPostRes()
}

type APIV2PermissionsEuEntitiesAdministrationGrantsPostRes interface {
	aPIV2PermissionsEuEntitiesAdministrationGrantsPostRes()
}

type APIV2PermissionsEuEntitiesGrantsPostRes interface {
	aPIV2PermissionsEuEntitiesGrantsPostRes()
}

type APIV2PermissionsIndirectGrantsPostRes interface {
	aPIV2PermissionsIndirectGrantsPostRes()
}

type APIV2PermissionsOperationsReferenceNumberGetRes interface {
	aPIV2PermissionsOperationsReferenceNumberGetRes()
}

type APIV2PermissionsPersonsGrantsPostRes interface {
	aPIV2PermissionsPersonsGrantsPostRes()
}

type APIV2PermissionsQueryAuthorizationsGrantsPostRes interface {
	aPIV2PermissionsQueryAuthorizationsGrantsPostRes()
}

type APIV2PermissionsQueryEntitiesRolesGetRes interface {
	aPIV2PermissionsQueryEntitiesRolesGetRes()
}

type APIV2PermissionsQueryEuEntitiesGrantsPostRes interface {
	aPIV2PermissionsQueryEuEntitiesGrantsPostRes()
}

type APIV2PermissionsQueryPersonalGrantsPostRes interface {
	aPIV2PermissionsQueryPersonalGrantsPostRes()
}

type APIV2PermissionsQueryPersonsGrantsPostRes interface {
	aPIV2PermissionsQueryPersonsGrantsPostRes()
}

type APIV2PermissionsQuerySubordinateEntitiesRolesPostRes interface {
	aPIV2PermissionsQuerySubordinateEntitiesRolesPostRes()
}

type APIV2PermissionsQuerySubunitsGrantsPostRes interface {
	aPIV2PermissionsQuerySubunitsGrantsPostRes()
}

type APIV2PermissionsSubunitsGrantsPostRes interface {
	aPIV2PermissionsSubunitsGrantsPostRes()
}

type APIV2RateLimitsGetRes interface {
	aPIV2RateLimitsGetRes()
}

type APIV2SecurityPublicKeyCertificatesGetRes interface {
	aPIV2SecurityPublicKeyCertificatesGetRes()
}

type APIV2SessionsBatchPostRes interface {
	aPIV2SessionsBatchPostRes()
}

type APIV2SessionsBatchReferenceNumberClosePostRes interface {
	aPIV2SessionsBatchReferenceNumberClosePostRes()
}

type APIV2SessionsGetRes interface {
	aPIV2SessionsGetRes()
}

type APIV2SessionsOnlinePostRes interface {
	aPIV2SessionsOnlinePostRes()
}

type APIV2SessionsOnlineReferenceNumberClosePostRes interface {
	aPIV2SessionsOnlineReferenceNumberClosePostRes()
}

type APIV2SessionsOnlineReferenceNumberInvoicesPostRes interface {
	aPIV2SessionsOnlineReferenceNumberInvoicesPostRes()
}

type APIV2SessionsReferenceNumberGetRes interface {
	aPIV2SessionsReferenceNumberGetRes()
}

type APIV2SessionsReferenceNumberInvoicesFailedGetRes interface {
	aPIV2SessionsReferenceNumberInvoicesFailedGetRes()
}

type APIV2SessionsReferenceNumberInvoicesGetRes interface {
	aPIV2SessionsReferenceNumberInvoicesGetRes()
}

type APIV2SessionsReferenceNumberInvoicesInvoiceReferenceNumberGetRes interface {
	aPIV2SessionsReferenceNumberInvoicesInvoiceReferenceNumberGetRes()
}

type APIV2SessionsReferenceNumberInvoicesInvoiceReferenceNumberUpoGetRes interface {
	aPIV2SessionsReferenceNumberInvoicesInvoiceReferenceNumberUpoGetRes()
}

type APIV2SessionsReferenceNumberInvoicesKsefKsefNumberUpoGetRes interface {
	aPIV2SessionsReferenceNumberInvoicesKsefKsefNumberUpoGetRes()
}

type APIV2SessionsReferenceNumberUpoUpoReferenceNumberGetRes interface {
	aPIV2SessionsReferenceNumberUpoUpoReferenceNumberGetRes()
}

type APIV2TestdataAttachmentPostRes interface {
	aPIV2TestdataAttachmentPostRes()
}

type APIV2TestdataAttachmentRevokePostRes interface {
	aPIV2TestdataAttachmentRevokePostRes()
}

type APIV2TestdataLimitsContextSessionDeleteRes interface {
	aPIV2TestdataLimitsContextSessionDeleteRes()
}

type APIV2TestdataLimitsContextSessionPostRes interface {
	aPIV2TestdataLimitsContextSessionPostRes()
}

type APIV2TestdataLimitsSubjectCertificateDeleteRes interface {
	aPIV2TestdataLimitsSubjectCertificateDeleteRes()
}

type APIV2TestdataLimitsSubjectCertificatePostRes interface {
	aPIV2TestdataLimitsSubjectCertificatePostRes()
}

type APIV2TestdataPermissionsPostRes interface {
	aPIV2TestdataPermissionsPostRes()
}

type APIV2TestdataPermissionsRevokePostRes interface {
	aPIV2TestdataPermissionsRevokePostRes()
}

type APIV2TestdataPersonPostRes interface {
	aPIV2TestdataPersonPostRes()
}

type APIV2TestdataPersonRemovePostRes interface {
	aPIV2TestdataPersonRemovePostRes()
}

type APIV2TestdataRateLimitsDeleteRes interface {
	aPIV2TestdataRateLimitsDeleteRes()
}

type APIV2TestdataRateLimitsPostRes interface {
	aPIV2TestdataRateLimitsPostRes()
}

type APIV2TestdataSubjectPostRes interface {
	aPIV2TestdataSubjectPostRes()
}

type APIV2TestdataSubjectRemovePostRes interface {
	aPIV2TestdataSubjectRemovePostRes()
}

type APIV2TokensGetRes interface {
	aPIV2TokensGetRes()
}

type APIV2TokensPostRes interface {
	aPIV2TokensPostRes()
}

type APIV2TokensReferenceNumberDeleteRes interface {
	aPIV2TokensReferenceNumberDeleteRes()
}

type APIV2TokensReferenceNumberGetRes interface {
	aPIV2TokensReferenceNumberGetRes()
}
