// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// Bearer provides Bearer security value.
	// Token dostępu uzyskany w wyniku operacji uwierzytelnienia.
	Bearer(ctx context.Context, operationName OperationName) (Bearer, error)
}

func (s *Client) securityBearer(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.Bearer(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"Bearer\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
