// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *InvoiceExportRequest) setDefaults() {
	{
		val := bool(false)
		s.OnlyMetadata.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OpenBatchSessionRequest) setDefaults() {
	{
		val := bool(false)
		s.OfflineMode.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SendInvoiceRequest) setDefaults() {
	{
		val := bool(false)
		s.OfflineMode.SetTo(val)
	}
}
