// Code generated by ogen, DO NOT EDIT.
package api

type AuthChallengePostRes interface {
	authChallengePostRes()
}

type AuthKsefTokenPostRes interface {
	authKsefTokenPostRes()
}

type AuthReferenceNumberGetRes interface {
	authReferenceNumberGetRes()
}

type AuthSessionsCurrentDeleteRes interface {
	authSessionsCurrentDeleteRes()
}

type AuthSessionsGetRes interface {
	authSessionsGetRes()
}

type AuthSessionsReferenceNumberDeleteRes interface {
	authSessionsReferenceNumberDeleteRes()
}

type AuthTokenRedeemPostRes interface {
	authTokenRedeemPostRes()
}

type AuthTokenRefreshPostRes interface {
	authTokenRefreshPostRes()
}

type AuthXadesSignaturePostRes interface {
	authXadesSignaturePostRes()
}

type CertificatesCertificateSerialNumberRevokePostRes interface {
	certificatesCertificateSerialNumberRevokePostRes()
}

type CertificatesEnrollmentsDataGetRes interface {
	certificatesEnrollmentsDataGetRes()
}

type CertificatesEnrollmentsPostRes interface {
	certificatesEnrollmentsPostRes()
}

type CertificatesEnrollmentsReferenceNumberGetRes interface {
	certificatesEnrollmentsReferenceNumberGetRes()
}

type CertificatesLimitsGetRes interface {
	certificatesLimitsGetRes()
}

type CertificatesQueryPostRes interface {
	certificatesQueryPostRes()
}

type CertificatesRetrievePostRes interface {
	certificatesRetrievePostRes()
}

type InvoicesExportsPostRes interface {
	invoicesExportsPostRes()
}

type InvoicesExportsReferenceNumberGetRes interface {
	invoicesExportsReferenceNumberGetRes()
}

type InvoicesKsefKsefNumberGetRes interface {
	invoicesKsefKsefNumberGetRes()
}

type InvoicesQueryMetadataPostRes interface {
	invoicesQueryMetadataPostRes()
}

type LimitsContextGetRes interface {
	limitsContextGetRes()
}

type LimitsSubjectGetRes interface {
	limitsSubjectGetRes()
}

type PeppolQueryGetRes interface {
	peppolQueryGetRes()
}

type PermissionsAttachmentsStatusGetRes interface {
	permissionsAttachmentsStatusGetRes()
}

type PermissionsAuthorizationsGrantsPermissionIdDeleteRes interface {
	permissionsAuthorizationsGrantsPermissionIdDeleteRes()
}

type PermissionsAuthorizationsGrantsPostRes interface {
	permissionsAuthorizationsGrantsPostRes()
}

type PermissionsCommonGrantsPermissionIdDeleteRes interface {
	permissionsCommonGrantsPermissionIdDeleteRes()
}

type PermissionsEntitiesGrantsPostRes interface {
	permissionsEntitiesGrantsPostRes()
}

type PermissionsEuEntitiesAdministrationGrantsPostRes interface {
	permissionsEuEntitiesAdministrationGrantsPostRes()
}

type PermissionsEuEntitiesGrantsPostRes interface {
	permissionsEuEntitiesGrantsPostRes()
}

type PermissionsIndirectGrantsPostRes interface {
	permissionsIndirectGrantsPostRes()
}

type PermissionsOperationsReferenceNumberGetRes interface {
	permissionsOperationsReferenceNumberGetRes()
}

type PermissionsPersonsGrantsPostRes interface {
	permissionsPersonsGrantsPostRes()
}

type PermissionsQueryAuthorizationsGrantsPostRes interface {
	permissionsQueryAuthorizationsGrantsPostRes()
}

type PermissionsQueryEntitiesRolesGetRes interface {
	permissionsQueryEntitiesRolesGetRes()
}

type PermissionsQueryEuEntitiesGrantsPostRes interface {
	permissionsQueryEuEntitiesGrantsPostRes()
}

type PermissionsQueryPersonalGrantsPostRes interface {
	permissionsQueryPersonalGrantsPostRes()
}

type PermissionsQueryPersonsGrantsPostRes interface {
	permissionsQueryPersonsGrantsPostRes()
}

type PermissionsQuerySubordinateEntitiesRolesPostRes interface {
	permissionsQuerySubordinateEntitiesRolesPostRes()
}

type PermissionsQuerySubunitsGrantsPostRes interface {
	permissionsQuerySubunitsGrantsPostRes()
}

type PermissionsSubunitsGrantsPostRes interface {
	permissionsSubunitsGrantsPostRes()
}

type RateLimitsGetRes interface {
	rateLimitsGetRes()
}

type SecurityPublicKeyCertificatesGetRes interface {
	securityPublicKeyCertificatesGetRes()
}

type SessionsBatchPostRes interface {
	sessionsBatchPostRes()
}

type SessionsBatchReferenceNumberClosePostRes interface {
	sessionsBatchReferenceNumberClosePostRes()
}

type SessionsGetRes interface {
	sessionsGetRes()
}

type SessionsOnlinePostRes interface {
	sessionsOnlinePostRes()
}

type SessionsOnlineReferenceNumberClosePostRes interface {
	sessionsOnlineReferenceNumberClosePostRes()
}

type SessionsOnlineReferenceNumberInvoicesPostRes interface {
	sessionsOnlineReferenceNumberInvoicesPostRes()
}

type SessionsReferenceNumberGetRes interface {
	sessionsReferenceNumberGetRes()
}

type SessionsReferenceNumberInvoicesFailedGetRes interface {
	sessionsReferenceNumberInvoicesFailedGetRes()
}

type SessionsReferenceNumberInvoicesGetRes interface {
	sessionsReferenceNumberInvoicesGetRes()
}

type SessionsReferenceNumberInvoicesInvoiceReferenceNumberGetRes interface {
	sessionsReferenceNumberInvoicesInvoiceReferenceNumberGetRes()
}

type SessionsReferenceNumberInvoicesInvoiceReferenceNumberUpoGetRes interface {
	sessionsReferenceNumberInvoicesInvoiceReferenceNumberUpoGetRes()
}

type SessionsReferenceNumberInvoicesKsefKsefNumberUpoGetRes interface {
	sessionsReferenceNumberInvoicesKsefKsefNumberUpoGetRes()
}

type SessionsReferenceNumberUpoUpoReferenceNumberGetRes interface {
	sessionsReferenceNumberUpoUpoReferenceNumberGetRes()
}

type TestdataAttachmentPostRes interface {
	testdataAttachmentPostRes()
}

type TestdataAttachmentRevokePostRes interface {
	testdataAttachmentRevokePostRes()
}

type TestdataLimitsContextSessionDeleteRes interface {
	testdataLimitsContextSessionDeleteRes()
}

type TestdataLimitsContextSessionPostRes interface {
	testdataLimitsContextSessionPostRes()
}

type TestdataLimitsSubjectCertificateDeleteRes interface {
	testdataLimitsSubjectCertificateDeleteRes()
}

type TestdataLimitsSubjectCertificatePostRes interface {
	testdataLimitsSubjectCertificatePostRes()
}

type TestdataPermissionsPostRes interface {
	testdataPermissionsPostRes()
}

type TestdataPermissionsRevokePostRes interface {
	testdataPermissionsRevokePostRes()
}

type TestdataPersonPostRes interface {
	testdataPersonPostRes()
}

type TestdataPersonRemovePostRes interface {
	testdataPersonRemovePostRes()
}

type TestdataRateLimitsDeleteRes interface {
	testdataRateLimitsDeleteRes()
}

type TestdataRateLimitsPostRes interface {
	testdataRateLimitsPostRes()
}

type TestdataRateLimitsProductionPostRes interface {
	testdataRateLimitsProductionPostRes()
}

type TestdataSubjectPostRes interface {
	testdataSubjectPostRes()
}

type TestdataSubjectRemovePostRes interface {
	testdataSubjectRemovePostRes()
}

type TokensGetRes interface {
	tokensGetRes()
}

type TokensPostRes interface {
	tokensPostRes()
}

type TokensReferenceNumberDeleteRes interface {
	tokensReferenceNumberDeleteRes()
}

type TokensReferenceNumberGetRes interface {
	tokensReferenceNumberGetRes()
}
