// Code generated by ogen, DO NOT EDIT.

package api

// AuthReferenceNumberGetParams is parameters of GET /auth/{referenceNumber} operation.
type AuthReferenceNumberGetParams struct {
	// Numer referencyjny tokena otrzymanego przy inicjalizacji operacji uwierzytelniania.
	ReferenceNumber ReferenceNumber
}

// AuthSessionsGetParams is parameters of GET /auth/sessions operation.
type AuthSessionsGetParams struct {
	// Token służący do pobrania kolejnej strony wyników.
	XContinuationToken OptString `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// AuthSessionsReferenceNumberDeleteParams is parameters of DELETE /auth/sessions/{referenceNumber} operation.
type AuthSessionsReferenceNumberDeleteParams struct {
	// Numer referencyjny sesji uwierzytelnienia.
	ReferenceNumber ReferenceNumber
}

// AuthXadesSignaturePostParams is parameters of POST /auth/xades-signature operation.
type AuthXadesSignaturePostParams struct {
	// Wymuszenie weryfikacji zaufania łańcucha certyfikatu wraz ze sprawdzeniem statusu certyfikatu
	// (OCSP/CRL) na środowiskach które umożliwiają wykorzystanie samodzielnie wygenerowanych
	// certyfikatów.
	VerifyCertificateChain OptBool `json:",omitempty,omitzero"`
}

// CertificatesCertificateSerialNumberRevokePostParams is parameters of POST /certificates/{certificateSerialNumber}/revoke operation.
type CertificatesCertificateSerialNumberRevokePostParams struct {
	// Numer seryjny certyfikatu (w formacie szesnastkowym).
	CertificateSerialNumber string
}

// CertificatesEnrollmentsReferenceNumberGetParams is parameters of GET /certificates/enrollments/{referenceNumber} operation.
type CertificatesEnrollmentsReferenceNumberGetParams struct {
	// Numer referencyjny wniosku certyfikacyjnego.
	ReferenceNumber ReferenceNumber
}

// CertificatesQueryPostParams is parameters of POST /certificates/query operation.
type CertificatesQueryPostParams struct {
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
}

// InvoicesExportsReferenceNumberGetParams is parameters of GET /invoices/exports/{referenceNumber} operation.
type InvoicesExportsReferenceNumberGetParams struct {
	// Numer referencyjny eksportu faktur.
	ReferenceNumber ReferenceNumber
}

// InvoicesKsefKsefNumberGetParams is parameters of GET /invoices/ksef/{ksefNumber} operation.
type InvoicesKsefKsefNumberGetParams struct {
	// Numer KSeF faktury.
	KsefNumber KsefNumber
}

// InvoicesQueryMetadataPostParams is parameters of POST /invoices/query/metadata operation.
type InvoicesQueryMetadataPostParams struct {
	// Kolejność sortowania wyników.
	// | Wartość | Opis |
	// | --- | --- |
	// | Asc | Sortowanie rosnąco. |
	// | Desc | Sortowanie malejąco. |.
	SortOrder OptSortOrder `json:",omitempty,omitzero"`
	// Indeks pierwszej strony wyników (0 = pierwsza strona).
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// PeppolQueryGetParams is parameters of GET /peppol/query operation.
type PeppolQueryGetParams struct {
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// PermissionsAuthorizationsGrantsPermissionIdDeleteParams is parameters of DELETE /permissions/authorizations/grants/{permissionId} operation.
type PermissionsAuthorizationsGrantsPermissionIdDeleteParams struct {
	// Id uprawnienia.
	PermissionId PermissionId
}

// PermissionsCommonGrantsPermissionIdDeleteParams is parameters of DELETE /permissions/common/grants/{permissionId} operation.
type PermissionsCommonGrantsPermissionIdDeleteParams struct {
	// Id uprawnienia.
	PermissionId PermissionId
}

// PermissionsOperationsReferenceNumberGetParams is parameters of GET /permissions/operations/{referenceNumber} operation.
type PermissionsOperationsReferenceNumberGetParams struct {
	// Numer referencyjny operacji nadania lub odbierania uprawnień.
	ReferenceNumber ReferenceNumber
}

// PermissionsQueryAuthorizationsGrantsPostParams is parameters of POST /permissions/query/authorizations/grants operation.
type PermissionsQueryAuthorizationsGrantsPostParams struct {
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// PermissionsQueryEntitiesRolesGetParams is parameters of GET /permissions/query/entities/roles operation.
type PermissionsQueryEntitiesRolesGetParams struct {
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// PermissionsQueryEuEntitiesGrantsPostParams is parameters of POST /permissions/query/eu-entities/grants operation.
type PermissionsQueryEuEntitiesGrantsPostParams struct {
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// PermissionsQueryPersonalGrantsPostParams is parameters of POST /permissions/query/personal/grants operation.
type PermissionsQueryPersonalGrantsPostParams struct {
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// PermissionsQueryPersonsGrantsPostParams is parameters of POST /permissions/query/persons/grants operation.
type PermissionsQueryPersonsGrantsPostParams struct {
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// PermissionsQuerySubordinateEntitiesRolesPostParams is parameters of POST /permissions/query/subordinate-entities/roles operation.
type PermissionsQuerySubordinateEntitiesRolesPostParams struct {
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// PermissionsQuerySubunitsGrantsPostParams is parameters of POST /permissions/query/subunits/grants operation.
type PermissionsQuerySubunitsGrantsPostParams struct {
	// Numer strony wyników.
	PageOffset OptInt32 `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// SessionsBatchReferenceNumberClosePostParams is parameters of POST /sessions/batch/{referenceNumber}/close operation.
type SessionsBatchReferenceNumberClosePostParams struct {
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
}

// SessionsGetParams is parameters of GET /sessions operation.
type SessionsGetParams struct {
	// Rozmiar strony.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Typ sesji.
	// | Wartość | Opis |
	// | --- | --- |
	// | Online | Wysyłka interaktywna (pojedyncze faktury). |
	// | Batch | Wysyłka wsadowa (paczka faktur). |.
	SessionType SessionType
	// Numer referencyjny sesji.
	ReferenceNumber OptReferenceNumber `json:",omitempty,omitzero"`
	// Data utworzenia sesji (od).
	DateCreatedFrom OptDateTime `json:",omitempty,omitzero"`
	// Data utworzenia sesji (do).
	DateCreatedTo OptDateTime `json:",omitempty,omitzero"`
	// Data zamknięcia sesji (od).
	DateClosedFrom OptDateTime `json:",omitempty,omitzero"`
	// Data zamknięcia sesji (do).
	DateClosedTo OptDateTime `json:",omitempty,omitzero"`
	// Data ostatniej aktywności (wysyłka faktury lub zmiana statusu) w ramach sesji (od).
	DateModifiedFrom OptDateTime `json:",omitempty,omitzero"`
	// Data ostatniej aktywności (wysyłka faktury lub zmiana statusu) w ramach sesji (do).
	DateModifiedTo OptDateTime `json:",omitempty,omitzero"`
	// Statusy sesji.
	// | Wartość | Opis |
	// | --- | --- |
	// | InProgress | Sesja aktywna. |
	// | Succeeded | Sesja przetworzona poprawnie.            W trakcie przetwarzania sesji nie
	// wystąpiły żadne błędy, ale część faktur nadal mogła zostać odrzucona. |
	// | Failed | Sesja nie przetworzona z powodu błędów.            Na etapie rozpoczynania lub
	// kończenia sesji wystąpiły błędy, które nie pozwoliły na jej poprawne przetworzenie. |
	// | Cancelled | Sesja anulowania.            Został przekroczony czas na wysyłkę w sesji wsadowej,
	//  lub nie przesłano żadnych faktur w sesji interaktywnej. |.
	Statuses []CommonSessionStatus `json:",omitempty"`
	// Token służący do pobrania kolejnej strony wyników.
	XContinuationToken OptString `json:",omitempty,omitzero"`
}

// SessionsOnlineReferenceNumberClosePostParams is parameters of POST /sessions/online/{referenceNumber}/close operation.
type SessionsOnlineReferenceNumberClosePostParams struct {
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
}

// SessionsOnlineReferenceNumberInvoicesPostParams is parameters of POST /sessions/online/{referenceNumber}/invoices operation.
type SessionsOnlineReferenceNumberInvoicesPostParams struct {
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
}

// SessionsReferenceNumberGetParams is parameters of GET /sessions/{referenceNumber} operation.
type SessionsReferenceNumberGetParams struct {
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
}

// SessionsReferenceNumberInvoicesFailedGetParams is parameters of GET /sessions/{referenceNumber}/invoices/failed operation.
type SessionsReferenceNumberInvoicesFailedGetParams struct {
	// Token służący do pobrania kolejnej strony wyników.
	XContinuationToken OptString `json:",omitempty,omitzero"`
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// SessionsReferenceNumberInvoicesGetParams is parameters of GET /sessions/{referenceNumber}/invoices operation.
type SessionsReferenceNumberInvoicesGetParams struct {
	// Token służący do pobrania kolejnej strony wyników.
	XContinuationToken OptString `json:",omitempty,omitzero"`
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
}

// SessionsReferenceNumberInvoicesInvoiceReferenceNumberGetParams is parameters of GET /sessions/{referenceNumber}/invoices/{invoiceReferenceNumber} operation.
type SessionsReferenceNumberInvoicesInvoiceReferenceNumberGetParams struct {
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
	// Numer referencyjny faktury.
	InvoiceReferenceNumber ReferenceNumber
}

// SessionsReferenceNumberInvoicesInvoiceReferenceNumberUpoGetParams is parameters of GET /sessions/{referenceNumber}/invoices/{invoiceReferenceNumber}/upo operation.
type SessionsReferenceNumberInvoicesInvoiceReferenceNumberUpoGetParams struct {
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
	// Numer referencyjny faktury.
	InvoiceReferenceNumber ReferenceNumber
}

// SessionsReferenceNumberInvoicesKsefKsefNumberUpoGetParams is parameters of GET /sessions/{referenceNumber}/invoices/ksef/{ksefNumber}/upo operation.
type SessionsReferenceNumberInvoicesKsefKsefNumberUpoGetParams struct {
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
	// Numer KSeF faktury.
	KsefNumber KsefNumber
}

// SessionsReferenceNumberUpoUpoReferenceNumberGetParams is parameters of GET /sessions/{referenceNumber}/upo/{upoReferenceNumber} operation.
type SessionsReferenceNumberUpoUpoReferenceNumberGetParams struct {
	// Numer referencyjny sesji.
	ReferenceNumber ReferenceNumber
	// Numer referencyjny UPO.
	UpoReferenceNumber ReferenceNumber
}

// TokensGetParams is parameters of GET /tokens operation.
type TokensGetParams struct {
	// Status tokenów do zwrócenia. W przypadku braku parametru zwracane są wszystkie tokeny. Parametr
	// można przekazać wielokrotnie.
	// | Wartość | Opis |
	// | --- | --- |
	// | Pending | Token został utworzony ale jest jeszcze w trakcie aktywacji i nadawania uprawnień.
	// Nie może być jeszcze wykorzystywany do uwierzytelniania. |
	// | Active | Token jest aktywny i może być wykorzystywany do uwierzytelniania. |
	// | Revoking | Token jest w trakcie unieważniania. Nie może już być wykorzystywany do
	// uwierzytelniania. |
	// | Revoked | Token został unieważniony i nie może być wykorzystywany do uwierzytelniania. |
	// | Failed | Nie udało się aktywować tokena. Należy wygenerować nowy token, obecny nie może
	// być wykorzystywany do uwierzytelniania. |.
	Status []AuthenticationTokenStatus `json:",omitempty"`
	// Umożliwia filtrowanie tokenów po opisie. Wartość parametru jest wyszukiwana w opisie tokena
	// (operacja nie rozróżnia wielkości liter). Należy podać co najmniej 3 znaki.
	Description OptString `json:",omitempty,omitzero"`
	// Umożliwia filtrowanie tokenów po ich twórcy. Wartość parametru jest wyszukiwana w
	// identyfikatorze (operacja nie rozróżnia wielkości liter). Należy podać co najmniej 3 znaki.
	AuthorIdentifier OptString `json:",omitempty,omitzero"`
	// Umożliwia filtrowanie tokenów po ich twórcy. Wartość parametru określa typ identyfikatora w
	// którym będzie wyszukiwany ciąg znaków przekazany w parametrze `authorIdentifier`.
	// | Wartość | Opis |
	// | --- | --- |
	// | Nip | NIP. |
	// | Pesel | PESEL. |
	// | Fingerprint | Odcisk palca certyfikatu. |.
	AuthorIdentifierType OptTokenAuthorIdentifierType `json:",omitempty,omitzero"`
	// Rozmiar strony wyników.
	PageSize OptInt32 `json:",omitempty,omitzero"`
	// Token służący do pobrania kolejnej strony wyników.
	XContinuationToken OptString `json:",omitempty,omitzero"`
}

// TokensReferenceNumberDeleteParams is parameters of DELETE /tokens/{referenceNumber} operation.
type TokensReferenceNumberDeleteParams struct {
	// Numer referencyjny tokena KSeF.
	ReferenceNumber ReferenceNumber
}

// TokensReferenceNumberGetParams is parameters of GET /tokens/{referenceNumber} operation.
type TokensReferenceNumberGetParams struct {
	// Numer referencyjny tokena KSeF.
	ReferenceNumber ReferenceNumber
}
